export const LandingVideosData = [
  {
    id: 1,
    clip: require("./assets/clip1.mp4"),
  },
  {
    id: 2,
    clip: require("./assets/clip2.mp4"),
  },
  {
    id: 3,
    clip: require("./assets/clip3.mp4"),
  },
];
export const PopularData = [
  {
    id: 1,
    title: "Nike Addapt BB",
    price: 20000,
    rate: "4.5",
    img: require("./assets/popular1.png"),
    year: "2022",
    sizes: "35-38-40-45-49",
    colors: "Red - Blue - Yellow",
    orders: "6,200",
    classN: "popular-1",
  },
  {
    id: 2,
    title: "Puma Martine Rose",
    price: 22000,
    rate: "5",
    img: require("./assets/popular2.png"),
    year: "2021",
    sizes: "35-38-42-45-49",
    colors: "Black - Red - Yellow",
    orders: "5,450",
    classN: "popular-2",
  },
  {
    id: 3,
    title: "Nike Smart Shoe",
    price: 15000,
    rate: "4.3",
    img: require("./assets/popular3.png"),
    year: "2022",
    sizes: "33-36-43-45-49",
    colors: "Purble - White - Red",
    orders: "5,000",
    classN: "popular-3",
  },
];
export const TopSalesData = [
  {
    id: 1,
    title: "Nike Air Low Premium",
    price: 200000,
    rate: "4.9",
    img: require("./assets/top1.png"),
    year: "2022",
    sizes: "33-36-43-45-49",
    colors: "Blue - White - Red",
    orders: "7,000",
    classN: "top-1",
  },
  {
    id: 3,
    title: "Puma Addapt BB Rose",
    price: 13000,
    rate: "5",
    img: require("./assets/top3.png"),
    year: "2022",
    sizes: "36-40-44-49-50",
    colors: "Red - Rose - White",
    orders: "8,000",
    classN: "top-3",
  },
  {
    id: 2,
    title: "Nike Air Force Green",
    price: 25000,
    rate: "4.7",
    img: require("./assets/top2.png"),
    year: "2020",
    sizes: "34-36-40-43-47",
    colors: "Green - Blue - Yellow",
    orders: "6.200",
    classN: "top-2",
  },
  {
    id: 4,
    title: "Adidas Air Premium",
    price: 22000,
    rate: "5",
    img: require("./assets/top4.png"),
    year: "2021",
    sizes: "33-36-43-45-49",
    colors: "Brown - Gold - White",
    orders: "4,000",
    classN: "top-4",
  },
  {
    id: 5,
    title: "Puma Adapt BB Pro",
    price: 24000,
    rate: "4.8",
    img: require("./assets/top5.png"),
    year: "2021",
    sizes: "31-34-42-44-47",
    colors: "Gold - White - Blue",
    orders: "3,000",
    classN: "top-5",
  },
  {
    id: 6,
    title: "Air Jordan PR3",
    price: 14000,
    rate: "4.4",
    img: require("./assets/top6.png"),
    year: "2022",
    sizes: "34-38-40-46-49",
    colors: "Blue - White - Red",
    orders: "7,000",
    classN: "top-6",
  },
  {
    id: 7,
    title: "Nike Multi Smart Shoe",
    price: 20000,
    rate: "4.9",
    img: require("./assets/top7.png"),
    year: "2022",
    sizes: "33-36-43-45-49",
    colors: "Yellow - White - Blue",
    orders: "7,000",
    classN: "top-7",
  },
  {
    id: 8,
    title: "Adidas Jordan Air Max",
    price: 18500,
    rate: "4.6",
    img: require("./assets/top8.png"),
    year: "2022",
    sizes: "34-38-42-45-48",
    colors: "Brown - Gold - Purble",
    orders: "5,000",
    classN: "top-8",
  },
  {
    id: 9,
    title: "Nike Old Max-x",
    price: 21000,
    rate: "5",
    img: require("./assets/top9.png"),
    year: "2020",
    sizes: "33-35-40-43-45",
    colors: "Blue - White - Red",
    orders: "8,000",
    classN: "top-9",
  },
  {
    id: 10,
    title: "Nike Lime Jordan 11",
    price: 17000,
    rate: "5",
    img: require("./assets/top10.png"),
    year: "2022",
    sizes: "33-36-43-45-49",
    colors: "Green - Yellow - White",
    orders: "7,200",
    classN: "top-10",
  },
  {
    id: 11,
    title: "Nike Air Black Max",
    price: 20000,
    rate: "4.9",
    img: require("./assets/top11.png"),
    year: "2022",
    sizes: "33-36-43-45-49",
    colors: "White - Black - Red",
    orders: "7,000",
    classN: "top-11",
  },
  {
    id: 12,
    title: "Nike Zoom Max",
    price: 25000,
    rate: "5",
    img: require("./assets/top12.png"),
    year: "2021",
    sizes: "31-35-40-45-47",
    colors: "Blue - Red - Yellow",
    orders: "4,500",
    classN: "top-12",
  },
];
export const BlogsData = [
  {
    id: 1,
    img: require("./assets/blog1.jpg"),
    rate: "5",
    time: "20 Mins",
    author: "Michael Le",
    title: "Bro’s Nike Zoom Freak 4",
    desc: "Arriving right time for the Fall,this upcoming take on the Zoom Freak 4 seemingly draws inspiration from Thanksgiving. Orange & brown, two staples of the holiday, are used throughout the upper, dressing the parts not bathed in shades of grey and provide cool look.",
  },
  {
    id: 2,
    img: require("./assets/blog2.jpg"),
    rate: "4.5",
    time: "50 Mins",
    author: "Jordan Mo",
    title: "Nike Air Max Plus",
    desc:"The Nike Air Max Plus has enjoyed the reveal of several colorways these last few of months. And as we officially embark on the Fall season, an additional set have been added to the calendar, including this newly-revealed grey and orange colorway.",
  },
  {
    id: 3,
    img: require("./assets/blog3.jpg"),
    rate: "4.8",
    time: "2 Hours",
    author: "Chris Joe",
    title: "Air Force 1 Low",
    desc: "The cool nighttime aesthetic seen here is applied to the tumbled black leather panels of the upper and perforated mesh construction of the tongue while Royal trim and forefoot Swooshes provide additional intrigue to the darkened palette and give extra styling.",
  },
  {
    id: 4,
    img: require("./assets/blog4.jpg"),
    rate: "4",
    time: "1 Day",
    author: "Janet Joe",
    title: "Hello Kity NO.4",
    desc: "The world of Sanrio is vast and replete with many an iconic character. Few among the family, though, rival the immense influence of Hello Kitty, who’s played mascot for everything from Pringles merchandise to sneaker collaborations.",
  },
  {
    id: 5,
    img: require("./assets/blog5.jpg"),
    rate: "4.2",
    time: "2 Days",
    author: "Josef Mo",
    title: "Jayson Tatum Debuts",
    desc: "Jordan Brands signature model for the past few years, Jayson Tatum will be dawning the Air Jordan 37 this season before attaining potentially his first signature sneaker with Jumpman, which he rumored to be in the works recently via his Twitter.",
  },
  {
    id: 6,
    img: require("./assets/blog6.jpg"),
    rate: "4.6",
    time: "2 Days",
    author: "Samuel Joe",
    title: "Nike Air Max 1 G Always Fresh",
    desc: "Introducing brand new Nike Air Max 1 Golf Always Fresh sneakers,brought to you by Nike.These stylish and durable sneakers deliver the perfect blend of comfort and performance, making them the ideal choice for all golf enthusiasts and lover.  ",
  },
  {
    id: 7,
    img: require("./assets/blog7.jpg"),
    rate: "5",
    time: "4 Days",
    author: "Richard Hindi",
    title: "Dunk Low 'Championship Court",
    desc: "Nike Dunk Low Championship Purple features a white leather upper with Championship Purple overlays and cool Swooshes.Nike embroidery at the heel pays tribute to the original 1985 design. At the base a white and purple sole adds the finishing touch and tyle.",
  },
  {
    id: 8,
    img: require("./assets/blog8.jpg"),
    rate: "4.7",
    time: "5 Days",
    author: "Mic Anderson",
    title: "Nike Sport Shoe",
    desc: "At the top of the stability scale are motion control running shoes. According to Fitzgerald, motion control running shoes have all the bells and whistles: a firm chunk of foam in the inner midsole, maximum arch support and a high heel drop  .",
  },
];
